<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\AppIcon\QAM.ico</ApplicationIcon>
    <Authors>Eryk Potocki</Authors>
    <Company>Independent project</Company>
    <AssemblyName>QAManager</AssemblyName>
    <Product>QA Manager</Product>
    <Title>QA Manager</Title>
    <Version>0.2.4</Version>
    <AssemblyVersion>0.2.4.0</AssemblyVersion>
    <FileVersion>0.2.4.0</FileVersion>
    <InformationalVersion>0.2.4</InformationalVersion>
    <Copyright>Copyright © 2026 Eryk Potocki. Wszelkie prawa zastrzeżone.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\ExplorerView.axaml.cs">
      <DependentUpon>ExplorerView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
